apiVersion: v1
kind: Secret
metadata:
  name: wc-service-secret
type: Opaque
data:
  rmq_host: Z29vc2Uucm1xMi5jbG91ZGFtcXAuY29t
  rmq_username: d2R6b2dxZGc=
  rmq_pass: d1hNdTVJc3dSZXJJRl9UYkl3dmNhUzZhdnhNbHpBWks=
  rmq_port: NTY3Mg==
  rmq_path: d2R6b2dxZGc=
